### ISSUE TITLE
it is not installing in laravel v9.x-dev

### ISSUE THREAD

**Issue by borun** [smokills/laravel-http-client-default-options#5]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - smokills/laravel-http-client-default-options[v2.0.0, ..., v2.0.2] require illuminate/http ^8.0 -> found illuminate/http[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires smokills/laravel-http-client-default-options ^2.0 -> satisfiable by smokills/laravel-http-client-default-options[v2.0.0, v2.0.1, v2.0.2].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require smokills/laravel-http-client-default-options:*" to figure out if any version is installable, or "composer require smokills/laravel-http-client-default-options:^2.1" if you know which you need.

**Comment by smokills** [comment]
Hi, and thanks for your interest in this package. 

However, what you have posted is due because you are trying to use an unsupported version of the Laravel framework (v9.x-dev) from this package.

As soon as the new major version of Laravel will be officially released, you will be able to use this package.
